version: '3.3'
services:
  proxy:
    image: 321436061201.dkr.ecr.us-east-2.amazonaws.com/testrunz-reverseproxy-image:latest
    container_name: myapp-node-proxy
    restart: always
    ports:
      - 80:80
    networks:
      app-network:
        ipv4_address: 172.20.0.4
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      app-network:
        ipv4_address: 172.20.0.5
  server:
    image: 321436061201.dkr.ecr.us-east-2.amazonaws.com/testrunz-server-image:latest
    container_name: myapp-node-server
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    volumes:
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
    networks:
      app-network:
        ipv4_address: 172.20.0.3
  client:
  # 1 for production Database; 2 for development database
    image: 321436061201.dkr.ecr.us-east-2.amazonaws.com/testrunz-client-image:latest
    container_name: myapp-react-client
    command: /usr/src/app/node_modules/.bin/nodemon app.js
    volumes:
      - /usr/src/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      app-network:
        ipv4_address: 172.20.0.2
networks:
  app-network:
    ipam:
      config:
        - subnet: 172.20.0.0/24
volumes:
  data-volume:
  node_modules:
  web-root:
    driver: local